FROM        --platform=$TARGETOS/$TARGETARCH node:22-bookworm-slim

LABEL       author="mallusrgreat" maintainer="mallusrgreat@gmail.com"

RUN         apt update \
            && apt -y install ffmpeg iproute2 git sqlite3 libsqlite3-dev python3 python3-dev ca-certificates dnsutils tzdata zip tar curl build-essential libtool iputils-ping libnss3 tini chromium libnss3 libxss1 libasound2 fonts-liberation libatk-bridge2.0-0 libgtk-3-0 libgbm-dev \
            && useradd -m -d /home/container container

            RUN         npm install npm@latest typescript ts-node @types/node --location=global

# install pnpm
RUN         npm install -g corepack
RUN         corepack enable
RUN         corepack prepare pnpm@latest --activate

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

STOPSIGNAL SIGINT

COPY        --chown=container:container ./../entrypoint.sh /entrypoint.sh
RUN         chmod +x /entrypoint.sh
ENTRYPOINT    ["/usr/bin/tini", "-g", "--"]
CMD         ["/entrypoint.sh"]
